services:
  - type: web
    name: telegram-bot
    env: docker
    repo: https://github.com/Legend1FR/fdfd.git
    region: oregon
    plan: starter
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: "/home/pptruser/.cache/puppeteer"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
      - key: RENDER_EXTERNAL_URL
        value: "https://fdfd-i8p9.onrender.com"
      - key: TZ
        value: "UTC"
      # إضافة متغيرات Telegram (اختيارية - يمكن تركها فارغة إذا كان session.txt موجود)
      - key: PHONE_NUMBER
        value: ""
      - key: PASSWORD
        value: ""
      - key: API_ID
        value: ""
      - key: API_HASH
        value: ""
    buildCommand: npm ci --only=production
    startCommand: node server.js
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
